### ISSUE TITLE
Feature Request: Wrap note tile and preview text alignment

### ISSUE THREAD

**Issue by tnaseem** [johansan/notebook-navigator#10]
Firstly, this extension is just what I needed. Great work!

**Note Title**
It would be good to have the option of allowing multiple lines for the note title - Either wrap the title, or have a similar option to the preview text, where you can specify the number of lines to show (default being 1).

**Preview text**
Place the preview text above the date, rather than on the right of the date, for a cleaner look.

**Comment by tnaseem** [comment]
In the interim, I've just added the following CSS snippet to clean things up on my end a bit. Not perfect, but it will do for now!:

```css
/* File name */
.nn-file-name {
  text-wrap: wrap;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

/* File date */
.nn-file-date {
  color: var(--text-muted) !important;
  font-size: 0.6rem;
  padding-top: 10px;
}
```
So, now it looks a bit cleaner (removed the preview text for now):

![Image](https://github.com/user-attachments/assets/a9806913-5762-435f-9ff3-0efbc55e3f8a)
